services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: S7r@ngP@ssw0rd!2025
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./server
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    volumes:
      - ./server:/app
      - .env:/app/.env 

  frontend:
    build: ./client
    ports:
      - "8081:80"
    depends_on:
      - backend
    volumes:
      - ./client:/app

volumes:
  mysql_data:

